from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter()

# Directory where CSV files are stored inside the Docker container.
_APP_OUT: Path = Path("/app/output")


def _serve_file(name: str) -> FileResponse:
    """
    Helper that returns `FileResponse` if the file exists,
    otherwise raises 404.
    """
    path = _APP_OUT / name
    if not path.exists():
        raise HTTPException(status_code=404, detail="file not found")
    return FileResponse(path, filename=name, media_type="text/csv")


@router.get("/download-csv")
async def download_csv():
    """Download the CSV generated by the /upload-csv endpoint."""
    return _serve_file("csv_predictions.csv")


@router.get("/download-youtube")
async def download_youtube():
    """Download the CSV generated by the /youtube-transcript endpoint."""
    return _serve_file("youtube_transcript.csv")


@router.get("/download-audio")
async def download_audio():
    """Download the CSV generated by the /upload-audio-transcript endpoint."""
    return _serve_file("uploaded_audio_transcript.csv")
